export const filterOptions = [
  { display: "HTML", key: "html" },
  { display: "CSS", key: "css" },
  { display: "Accessibility", key: "accessibility" },
  { display: "JavaScript", key: "javaScript" },
  { display: "React", key: "react" },
  { display: "Python", key: "python" },
  { display: "DataViz", key: "dataViz" },
  { display: "Made by Skillcrush", key: "skillcrush" },
];

export const resources = [
  {
    id: 1,
    name: "Flexbook Froggy",
    url: "https://flexboxfroggy.com/",
    imageSrc: "/img/game.png",
    alt: "game",
    html: false,
    css: true,
    javaScript: false,
    react: false,
    python: false,
    dataViz: false,
    skillcrush: false,
  },
  {
    id: 2,
    name: "Front End Development + React JavaScript",
    url: "https://skillcrush.com/blueprint/front-end-development-with-react-js-course/",
    imageSrc: "/img/course.png",
    alt: "course",
    html: true,
    css: true,
    accessibility: false,
    javaScript: true,
    react: true,
    python: false,
    dataViz: false,
    skillcrush: true,
  },
  {
    id: 3,
    name: "How to check your web accessibility for free",
    url: "https://silktide.com/blog/how-to-check-your-web-accessibility-for-free/",
    imageSrc: "/img/blog_or_docs.png",
    alt: "blog or docs",
    html: false,
    css: false,
    accessibility: true,
    javaScript: false,
    react: false,
    python: false,
    dataViz: false,
    skillcrush: false,
  },
  {
    id: 4,
    name: "Real Talk on Web Accessibility with Marcy Sutton Todd",
    url: "https://syntax.fm/show/836/real-talk-on-web-accessibility-with-marcy-sutton-todd",
    imageSrc: "/img/podcast.png",
    alt: "podcast",
    html: false,
    css: false,
    accessibility: true,
    javaScript: false,
    react: false,
    python: false,
    dataViz: false,
    skillcrush: false,
  },
  {
    id: 5,
    name: "Frontend Mentor",
    url: "https://www.frontendmentor.io/",
    imageSrc: "/img/project.png",
    alt: "project",
    html: true,
    css: true,
    accessibility: true,
    javaScript: true,
    react: false,
    python: false,
    dataViz: false,
    skillcrush: false,
  },
  {
    id: 6,
    name: "Python for Web Apps and Data",
    url: "https://skillcrush.com/blueprint/python-web-apps-data-course/",
    imageSrc: "/img/course.png",
    alt: "course",
    html: false,
    css: false,
    accessibility: false,
    javaScript: false,
    react: false,
    python: true,
    dataViz: true,
    skillcrush: true,
  },
  {
    id: 7,
    name: "JavaScript 30",
    url: "https://javascript30.com/",
    imageSrc: "/img/course.png",
    alt: "course",
    html: false,
    css: false,
    accessibility: false,
    javaScript: true,
    react: false,
    python: false,
    dataViz: false,
    skillcrush: false,
  },
  {
    id: 8,
    name: "CSS Flexbook Layout Guide",
    url: "https://css-tricks.com/snippets/css/a-guide-to-flexbox/",
    imageSrc: "/img/blog_or_docs.png",
    alt: "blog or docs",
    html: false,
    css: true,
    accessibility: false,
    javaScript: false,
    react: false,
    python: false,
    dataViz: false,
    skillcrush: false,
  },
  {
    id: 9,
    name: "Wes Bos' Course on Flexbox",
    url: "https://flexbox.io/",
    imageSrc: "/img/course.png",
    alt: "course",
    html: false,
    css: true,
    accessibility: false,
    javaScript: false,
    react: false,
    python: false,
    dataViz: false,
    skillcrush: false,
  },
  {
    id: 10,
    name: "An Interactive Guide to Flexbox",
    url: "https://www.joshwcomeau.com/css/interactive-guide-to-flexbox/",
    imageSrc: "/img/blog_or_docs.png",
    alt: "blog or docs",
    html: false,
    css: true,
    accessibility: false,
    javaScript: false,
    react: false,
    python: false,
    dataViz: false,
    skillcrush: false,
  },
  {
    id: 11,
    name: "Chrome DevTools and Flexbox Docs",
    url: "https://developer.chrome.com/docs/devtools/css/",
    imageSrc: "/img/blog_or_docs.png",
    alt: "blog or docs",
    html: false,
    css: true,
    accessibility: false,
    javaScript: false,
    react: false,
    python: false,
    dataViz: false,
    skillcrush: false,
  },
  {
    id: 12,
    name: "Flexbox Playground",
    url: "https://codepen.io/enxaneta/full/adLPwv/",
    imageSrc: "/img/blog_or_docs.png",
    alt: "blog or docs",
    html: false,
    css: true,
    accessibility: false,
    javaScript: false,
    react: false,
    python: false,
    dataViz: false,
    skillcrush: false,
  },
  {
    id: 13,
    name: "devChallenges",
    url: "https://devchallenges.io/",
    imageSrc: "/img/project.png",
    alt: "project",
    html: true,
    css: true,
    accessibility: true,
    javaScript: true,
    react: true,
    python: true,
    dataViz: false,
    skillcrush: false,
  },
  {
    id: 14,
    name: "iCodeThis",
    url: "https://icodethis.com/",
    imageSrc: "/img/project.png",
    alt: "project",
    html: true,
    css: true,
    accessibility: true,
    javaScript: true,
    react: true,
    python: false,
    dataViz: false,
    skillcrush: false,
  },
  {
    id: 15,
    name: "Codier",
    url: "https://codier.io/",
    imageSrc: "/img/project.png",
    alt: "project",
    html: true,
    css: true,
    accessibility: true,
    javaScript: true,
    react: true,
    python: false,
    dataViz: false,
    skillcrush: false,
  },
  {
    id: 16,
    name: "Chingu",
    url: "https://www.chingu.io/",
    imageSrc: "/img/project.png",
    alt: "project",
    html: true,
    css: true,
    accessibility: true,
    javaScript: true,
    react: true,
    python: true,
    dataViz: false,
    skillcrush: false,
  },
  {
    id: 17,
    name: "React Docs",
    url: "https://react.dev/",
    imageSrc: "/img/blog_or_docs.png",
    alt: "blog or docs",
    html: false,
    css: false,
    accessibility: false,
    javaScript: true,
    react: true,
    python: false,
    dataViz: false,
    skillcrush: false,
  },
  {
    id: 18,
    name: "React Visualized",
    url: "https://react.gg/visualized",
    imageSrc: "/img/blog_or_docs.png",
    alt: "blog or docs",
    html: false,
    css: false,
    accessibility: false,
    javaScript: true,
    react: true,
    python: false,
    dataViz: false,
    skillcrush: false,
  },
  {
    id: 19,
    name: "Accessible U",
    url: "https://accessibility.umn.edu/creating-accessible-content/develop-accessible-websites-applications",
    imageSrc: "/img/blog_or_docs.png",
    alt: "blog or docs",
    html: true,
    css: true,
    accessibility: true,
    javaScript: false,
    react: false,
    python: false,
    dataViz: false,
    skillcrush: false,
  },
  {
    id: 20,
    name: "allyphant",
    url: "https://a11yphant.com/",
    imageSrc: "/img/course.png",
    alt: "course",
    html: true,
    css: false,
    accessibility: true,
    javaScript: false,
    react: false,
    python: false,
    dataViz: false,
    skillcrush: false,
  },
  {
    id: 21,
    name: "Evergreen Data",
    url: "https://stephanieevergreen.com/blog/",
    imageSrc: "/img/blog_or_docs.png",
    alt: "blog or docs",
    html: false,
    css: false,
    accessibility: false,
    javaScript: false,
    react: false,
    python: false,
    dataViz: true,
    skillcrush: false,
  },
  {
    id: 22,
    name: "Front End Development",
    url: "https://skillcrush.com/blueprint/front-end-development-course/",
    imageSrc: "/img/course.png",
    alt: "course",
    html: true,
    css: true,
    accessibility: false,
    javaScript: true,
    react: false,
    python: false,
    dataViz: false,
    skillcrush: true,
  },
  {
    id: 23,
    name: "21 Easy JavaScript Projects for Beginners (Code included!)",
    url: "https://skillcrush.com/blog/projects-you-can-do-with-javascript/",
    imageSrc: "/img/project.png",
    alt: "project",
    html: false,
    css: false,
    accessibility: false,
    javaScript: true,
    react: false,
    python: false,
    dataViz: false,
    skillcrush: true,
  },
  {
    id: 24,
    name: "Flexbook Zombie",
    url: "https://flexboxzombies.com/p/flexbox-zombies",
    imageSrc: "/img/game.png",
    alt: "game",
    html: false,
    css: true,
    javaScript: false,
    react: false,
    python: false,
    dataViz: false,
    skillcrush: false,
  },


];
